## Complete Pytorch Tensor Tutorial

In [1]:
import torch

In [6]:
my_tensor = torch.tensor([[1,2,3], [4,5,6]], dtype=torch.float32)

In [7]:
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

we can put this tensors on perticular device like, `cuda` or `mps` default is `cpu`

- check for availability of device

In [11]:
# check for MSP then for cuda and default is cpu
device = "cpu"

if torch.backends.mps.is_built() and torch.backends.mps.is_available():
    device = "mps"
elif torch.cuda.is_available():
    device = "cuda"

print(f"Device : {device}")

Device : mps


In [12]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]], device=device)

In [13]:
my_tensor

tensor([[1, 2, 3],
        [4, 5, 6]], device='mps:0')

- let's check attributes associated with the tensors

In [16]:
print(my_tensor.dtype)

torch.int64


In [17]:
print(my_tensor.device)

mps:0


In [18]:
print(my_tensor.shape)

torch.Size([2, 3])


- Other common initalization methods

In [21]:
x = torch.empty(size=(2, 3)) # will initallize with shape with random values

In [22]:
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [23]:
x = torch.zeros(size=(2, 3)) # initalize tensors with zeros

In [24]:
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [25]:
x = torch.ones(size=(2, 3)) # initalize tensors with once

In [26]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [31]:
x = torch.rand((2, 3)) # random values

In [32]:
x

tensor([[0.3491, 0.7817, 0.1986],
        [0.7839, 0.3069, 0.5328]])

- Identity matrix

In [36]:
x = torch.eye(3) # shape should be square

In [37]:
x

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [38]:
x = torch.arange(start=0, end=5, step=1)

In [39]:
x

tensor([0, 1, 2, 3, 4])

In [50]:
x = torch.linspace(start=0.1, end=1, steps=100)

In [51]:
x

tensor([0.1000, 0.1091, 0.1182, 0.1273, 0.1364, 0.1455, 0.1545, 0.1636, 0.1727,
        0.1818, 0.1909, 0.2000, 0.2091, 0.2182, 0.2273, 0.2364, 0.2455, 0.2545,
        0.2636, 0.2727, 0.2818, 0.2909, 0.3000, 0.3091, 0.3182, 0.3273, 0.3364,
        0.3455, 0.3545, 0.3636, 0.3727, 0.3818, 0.3909, 0.4000, 0.4091, 0.4182,
        0.4273, 0.4364, 0.4455, 0.4545, 0.4636, 0.4727, 0.4818, 0.4909, 0.5000,
        0.5091, 0.5182, 0.5273, 0.5364, 0.5455, 0.5545, 0.5636, 0.5727, 0.5818,
        0.5909, 0.6000, 0.6091, 0.6182, 0.6273, 0.6364, 0.6455, 0.6545, 0.6636,
        0.6727, 0.6818, 0.6909, 0.7000, 0.7091, 0.7182, 0.7273, 0.7364, 0.7455,
        0.7545, 0.7636, 0.7727, 0.7818, 0.7909, 0.8000, 0.8091, 0.8182, 0.8273,
        0.8364, 0.8455, 0.8545, 0.8636, 0.8727, 0.8818, 0.8909, 0.9000, 0.9091,
        0.9182, 0.9273, 0.9364, 0.9455, 0.9545, 0.9636, 0.9727, 0.9818, 0.9909,
        1.0000])

- get normally distributed numbers

In [52]:
x = torch.empty((2, 3)).normal_(mean=0, std=1)

In [53]:
x

tensor([[ 0.1358,  0.4942,  0.2636],
        [ 1.5269,  0.9821, -0.2510]])

- get tensors from uniform distribution

In [54]:
x = torch.empty((2, 3)).uniform_(0, 1)

In [55]:
x

tensor([[0.8274, 0.5311, 0.7769],
        [0.7361, 0.9676, 0.9799]])

In [58]:
torch.diag(torch.ones(5))

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

- how to initalize and convert tensors to other types (int , float, double, long)

In [59]:
tesnor = torch.arange(4)

In [60]:
tesnor

tensor([0, 1, 2, 3])

In [61]:
tesnor.bool() # boolean True/ False

tensor([False,  True,  True,  True])

In [62]:
tesnor.short() # int16

tensor([0, 1, 2, 3], dtype=torch.int16)

In [64]:
tesnor.long() # int64 (Inportant)

tensor([0, 1, 2, 3])

In [65]:
tesnor.half() # float16

tensor([0., 1., 2., 3.], dtype=torch.float16)

In [68]:
tesnor.float() # float32 (Important)

tensor([0., 1., 2., 3.])

In [69]:
tesnor.double() # float64

tensor([0., 1., 2., 3.], dtype=torch.float64)

## Array to tensor conversion

In [71]:
import numpy as np

In [73]:
np_array = np.zeros((5, 5))

In [74]:
np_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

- numpy array --> tensor

In [75]:
tensor = torch.from_numpy(np_array)

In [76]:
tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)

- torch tensor --> numpy array

In [77]:
numpy_array_back = tensor.numpy()

In [78]:
numpy_array_back

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Tensor Math & Comparison Operations

In [79]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])

### Addition

In [80]:
z1 = torch.zeros(3)

In [81]:
z1

tensor([0., 0., 0.])

In [82]:
torch.add(x, y, out=z1)

tensor([10., 10., 10.])

In [83]:
z1

tensor([10., 10., 10.])

In [84]:
# other way around
z2 = torch.add(x, y)

In [85]:
z2

tensor([10, 10, 10])

In [86]:
# preffered and clean way

z = x + y

In [87]:
z

tensor([10, 10, 10])

### Subtraction

In [88]:
z = x - y

In [89]:
z

tensor([-8, -6, -4])

### Division

In [90]:
z = torch.true_divide(x, y) # it divide x/y element wise, if there shape are same

In [91]:
z

tensor([0.1111, 0.2500, 0.4286])

if x = [1, 2, 3] y = 3

In [94]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([9])

In [95]:
torch.true_divide(a, b) # 1/9, 2/9, 3/9

tensor([0.1111, 0.2222, 0.3333])

## Inplace Operation

In [98]:
t = torch.zeros(3)

In [99]:
t

tensor([0., 0., 0.])

- when ever we see `_` mean that operation is inplace operation

In [100]:
t.add_(x) 

tensor([1., 2., 3.])

In [101]:
t += x # t = t + x

In [102]:
t

tensor([2., 4., 6.])